### ISSUE TITLE
Support regular (non-threaded) chats

### ISSUE THREAD

**Issue by Red-Teapot** [Red-Teapot/MinecraftTelegramChatBridge#13]

**Comment by MikeWent** [comment]
Addition: ignore messages with empty Thread ID.

```
WARN: [TelegramBridge] Could not send Minecraft message
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "org.telegram.telegrambots.meta.api.objects.Message.getMessageThreadId()" is null
 at me.redteapot.tgbridge.BridgeTelegramBot.onUpdateReceived(BridgeTelegramBot.java:32) ~[tg-bridge-v0.0.2.jar:?]
 at java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
 at org.telegram.telegrambots.meta.generics.LongPollingBot.onUpdatesReceived(LongPollingBot.java:27) ~[tg-bridge-v0.0.2.jar:?]
 at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$HandlerThread.run(DefaultBotSession.java:312) ~[tg-bridge-v0.0.2.jar:?]
 ```
